version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auction_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  supply_side_service:
    build:
      context: ./path_to_supply_side_service
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  demand_side_service:
    build:
      context: ./path_to_demand_side_service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
